#ifndef DEFAULTLIST_H
#define DEFAULTLIST_H
namespace defaultlist {
static const char* const json ="{"
    "    \"data\": ["
    "        {"
    "            \"casaProd\": \"SigmaSV\","
    "            \"codice\": \"1C56Y\","
    "            \"discount\": 25,"
    "            \"img64\": \"\","
    "            \"istoxic\": false,"
    "            \"nome\": \"Sample ProdChimico\","
    "            \"prezzo\": 10,"
    "            \"quantitaml\": 500,"
    "            \"type\": \"11ProdChimico\""
    "        },"
    "        {"
    "            \"casaProd\": \"SigmaSV\","
    "            \"codice\": \"1D213C\","
    "            \"discount\": 10,"
    "            \"img64\": \"\","
    "            \"istoxic\": false,"
    "            \"nome\": \"Sample Shampoo\","
    "            \"prezzo\": 16.73,"
    "            \"quantitaml\": 300,"
    "            \"tipoCap\": \"GENERALE\","
    "            \"tipoSha\": \"ANTICADUTA\","
    "            \"type\": \"7Shampoo\""
    "        },"
    "        {"
    "            \"casaProd\": \"SigmaSV\","
    "            \"codice\": \"694LIFE\","
    "            \"discount\": 0,"
    "            \"img64\": \"/home/student/Downloads/index.jpeg\","
    "            \"istoxic\": false,"
    "            \"nome\": \"Sample Tinta\","
    "            \"numero\": \"00\","
    "            \"prezzo\": 15,"
    "            \"quantitaml\": 150,"
    "            \"tipoTT\": \"CREMA\","
    "            \"type\": \"5Tinte\""
    "        },"
    "        {"
    "            \"casaProd\": \"SigmaSV\","
    "            \"codice\": \"420\","
    "            \"discount\": 0,"
    "            \"img64\": \"\","
    "            \"istoxic\": false,"
    "            \"nome\": \"Sample ShamColor\","
    "            \"numero\": \"6.00\","
    "            \"prezzo\": 23,"
    "            \"quantitaml\": 350,"
    "            \"tipoCap\": \"GENERALE\","
    "            \"tipoSha\": \"COLORANTE\","
    "            \"tipoTT\": \"OLIO\","
    "            \"type\": \"9ShamColor\""
    "        }"
    "    ]"
    "}";
}
#endif // DEFAULTLIST_H
